### ISSUE TITLE
[1.7.10] Incompatibility with makamys' fork of RenderPlayerAPI

### ISSUE THREAD

**Issue by Gronglegrowth** [exaskye/Ears#112] opened 2023-02-03 23:38 UTC
When Ears v1.4.5_01 is loaded alongside [this fork of RenderPlayerAPI](https://github.com/makamys/RenderPlayerAPI), the game will crash on entering a world.

[crash-2023-02-03_18.27.02-client.txt](https://github.com/unascribed/Ears/files/10583549/crash-2023-02-03_18.27.02-client.txt)

**Comment by makamys** [comment] 2023-02-05 17:34
This is a duplicate of #34. My fork doesn't contain any functional changes, it's just a mirror for easy access by build scripts.

**Closed as completed** 2023-02-06 15:50 UTC
Labels: s: Duplicate
