### ISSUE TITLE
Forge 1.8.9 mod not properly processing Erase Regions

### ISSUE THREAD

**Issue by NickAcPT** [exaskye/Ears#113] opened 2023-02-08 18:06 UTC
## Description

The 1.8 Forge port of the Ears mod doesn't seem to be processing the Erase Regions at all. The game doesn't crash or throw any errors on the [game log](https://mclo.gs/Hgs5btT).

### Actual
![Actual](https://user-images.githubusercontent.com/32451103/217604028-ae05e6cf-3a9b-4b68-b89e-3d484cb85c19.png)

### Expectation
![Expectation](https://user-images.githubusercontent.com/32451103/217603906-ffd70566-56ca-4004-9890-c2d2e14a89ba.png)

## To Reproduce

![Skin File](https://user-images.githubusercontent.com/32451103/217603375-01c3fcf9-45d1-4e34-bcac-d22d45287ed0.png)

## Files
The [ears-debug.log](https://github.com/unascribed/Ears/files/10688572/ears-debug.log) file.

I have tried to get Ears to output a debug log with the JVM argument `-Dears.debug=true` but the game crashes with [this](https://mclo.gs/mCaaHab) log when the debug output is enabled.

**Comment by exaskye** [comment] 2023-02-09 20:38
Strange.

I'll keep an eye out for this in the 2.0 rewrite.

**Comment by exaskye** [comment] 2023-03-15 20:35
Just realizing this is a dupe of #99.

**Closed as not planned by exaskye** 2023-03-15 20:35 UTC
Labels: s: Duplicate
